### PR TITLE
Cleaning up some warnings

### PR DESCRIPTION
**Pull request by kkacprzak**
Changes in code introduced to remove C++ warnings reported during compilation.
I tackle with most of them, but some still remains, more details on [redmine](http://sphinx.if.uj.edu.pl/redmine/issues/1379)

### CODE REVIEW

**Comment by JPETTomographyTester** [comment]
Found 27 violations:

**Reporter**: cppcheck-raporter
**Rule**: uninitMemberVar
**Severity**: WARN
**File**: Actions/RunAction.cpp L25

Member variable &#39;RunAction::fHistoManager&#39; is not initialized in the constructor.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1731099732>*

**Reporter**: cppcheck-raporter
**Rule**: uninitMemberVar
**Severity**: WARN
**File**: Core/HistoManager.cpp L29

Member variable &#39;HistoManager::fStats&#39; is not initialized in the constructor.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a524963078>*

**Reporter**: cppcheck-raporter
**Rule**: useInitializationList
**Severity**: INFO
**File**: Core/HistoManager.cpp L42

Variable &#39;fErrorCounts&#39; is assigned in constructor body. Consider performing initialization in initialization list.. When an object of a class is created, the constructors of all member variables are called consecutively in the order the variables are declared, even if you don&#39;t explicitly write them to the initialization list. You could avoid assigning &#39;fErrorCounts&#39; a value by passing the value to the constructor in the initialization list.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1101694448>*

**Reporter**: cppcheck-raporter
**Rule**: copyCtorPointerCopying
**Severity**: INFO
**File**: Core/HistoManager.cpp L38

Value of pointer &#39;fEventPack&#39;, which points to allocated memory, is copied in copy constructor instead of allocating new memory.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1023737728>*

**Reporter**: cppcheck-raporter
**Rule**: multiCondition
**Severity**: INFO
**File**: Info/EventMessenger.cpp L107

Expression is always false because &#39;else if&#39; condition matches previous condition at line 97.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-971296330>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L76

The function &#39;AppendStep&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a363239767>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L37

The function &#39;BeginOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a19972639>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L31

The function &#39;BeginOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a523678720>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/ActionInitialization.cpp L30

The function &#39;Build&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-62365817>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/ActionInitialization.cpp L28

The function &#39;BuildForMaster&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a925702335>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L51

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a438309254>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Framework/JPetGeantEventPack.cpp L31

The function &#39;ConstructNextDecayTree&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1220859233>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L93

The function &#39;ConstructSDandField&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a194200576>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/RunManager.cpp L19

The function &#39;DoEventLoop&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1862041832>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L47

The function &#39;EndOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1589345352>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L58

The function &#39;EndOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a3544809>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/PrimaryGeneratorAction.cpp L52

The function &#39;GeneratePrimaries&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-88059260>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L63

The function &#39;MergeTrajectory&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a29210427>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/TrackingAction.cpp L29

The function &#39;PostUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a878309667>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/TrackingAction.cpp L22

The function &#39;PreUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1172660541>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Info/PrimaryParticleInformation.cpp L40

The function &#39;Print&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1096778167>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorSD.cpp L47

The function &#39;ProcessHits&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a770530160>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L125

The function &#39;ReturnNumberOfScintillators&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1333459719>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L150

The function &#39;SetDirectComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a684858466>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Info/DetectorConstructionMessenger.cpp L64

The function &#39;SetNewValue&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2071902771>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L131

The function &#39;SetoPsComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1678844371>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/SteppingAction.cpp L34

The function &#39;UserSteppingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-137044244>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 24 violations:

**Reporter**: cppcheck-raporter
**Rule**: uninitMemberVar
**Severity**: WARN
**File**: Actions/RunAction.cpp L25

Member variable &#39;RunAction::fHistoManager&#39; is not initialized in the constructor.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1731099732>*

**Reporter**: cppcheck-raporter
**Rule**: noCopyConstructor
**Severity**: INFO
**File**: Core/HistoManager.h L56

&#39;class HistoManager&#39; does not have a copy constructor which is recommended since the class contains a pointer to allocated memory.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-938224452>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L76

The function &#39;AppendStep&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a363239764>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L37

The function &#39;BeginOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a19972636>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L31

The function &#39;BeginOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a523678717>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/ActionInitialization.cpp L30

The function &#39;Build&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-62365820>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/ActionInitialization.cpp L28

The function &#39;BuildForMaster&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a925702332>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L51

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-678597648>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Framework/JPetGeantEventPack.cpp L31

The function &#39;ConstructNextDecayTree&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-593571879>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L93

The function &#39;ConstructSDandField&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a976095866>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/RunManager.cpp L19

The function &#39;DoEventLoop&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1862041835>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L47

The function &#39;EndOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1589345349>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L58

The function &#39;EndOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a3544806>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/PrimaryGeneratorAction.cpp L52

The function &#39;GeneratePrimaries&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-88059263>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L63

The function &#39;MergeTrajectory&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a29210424>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/TrackingAction.cpp L29

The function &#39;PostUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a878309664>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/TrackingAction.cpp L22

The function &#39;PreUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1172660538>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Info/PrimaryParticleInformation.cpp L40

The function &#39;Print&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1096778143>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorSD.cpp L47

The function &#39;ProcessHits&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a770530136>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/DetectorConstruction.cpp L125

The function &#39;ReturnNumberOfScintillators&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1333459743>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L150

The function &#39;SetDirectComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a684858463>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Info/DetectorConstructionMessenger.cpp L64

The function &#39;SetNewValue&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2071902768>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L131

The function &#39;SetoPsComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1678844374>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/SteppingAction.cpp L34

The function &#39;UserSteppingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-137044247>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by kdulski** [comment]
Could you also remove never used warnings? Or do we do it in separate PR?

**Review by kdulski — APPROVED** [review]

**Comment by JPETTomographyTester** [comment]
Found 24 violations:

**Reporter**: cppcheck-raporter
**Rule**: uninitMemberVar
**Severity**: WARN
**File**: Actions/RunAction.cpp L25

Member variable &#39;RunAction::fHistoManager&#39; is not initialized in the constructor.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1731099732>*

**Reporter**: cppcheck-raporter
**Rule**: noCopyConstructor
**Severity**: INFO
**File**: Core/HistoManager.h L56

&#39;class HistoManager&#39; does not have a copy constructor which is recommended since the class contains a pointer to allocated memory.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-938224452>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L78

The function &#39;AppendStep&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a279839064>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L38

The function &#39;BeginOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2093072132>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L32

The function &#39;BeginOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2004671069>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/ActionInitialization.cpp L32

The function &#39;Build&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1395348412>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/ActionInitialization.cpp L29

The function &#39;BuildForMaster&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1555006530>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L52

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1427185650>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Framework/JPetGeantEventPack.cpp L32

The function &#39;ConstructNextDecayTree&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a544033081>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L95

The function &#39;ConstructSDandField&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1562310654>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/RunManager.cpp L20

The function &#39;DoEventLoop&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-840771991>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/EventAction.cpp L49

The function &#39;EndOfEventAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1556246277>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/RunAction.cpp L60

The function &#39;EndOfRunAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a488333830>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/PrimaryGeneratorAction.cpp L53

The function &#39;GeneratePrimaries&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1824002657>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Objects/Geant4/Trajectory.cpp L64

The function &#39;MergeTrajectory&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-707459048>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/TrackingAction.cpp L31

The function &#39;PostUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1557967730>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/TrackingAction.cpp L23

The function &#39;PreUserTrackingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a173590938>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Info/PrimaryParticleInformation.cpp L41

The function &#39;Print&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-160959971>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorSD.cpp L48

The function &#39;ProcessHits&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1916209514>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L128

The function &#39;ReturnNumberOfScintillators&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a128988737>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L152

The function &#39;SetDirectComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1313280737>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Info/DetectorConstructionMessenger.cpp L65

The function &#39;SetNewValue&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1683048016>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Core/MaterialParameters.cpp L132

The function &#39;SetoPsComponents&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a509503272>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: Actions/SteppingAction.cpp L35

The function &#39;UserSteppingAction&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2051303399>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by kkacprzak** [comment]
It seems that adding inline comments did not result in suppressing of some warnings. How cpp-check is run? Can we try adding --inline-suppr flag to command?

**Comment by kdulski** [comment]
I will look at it, maybe it would be possible to add that by myself. Otherwise I will call a higher instance.

**Comment by kdulski** [comment]
Higher instance (Alek) added appropriate option to cpp-checker.
Could You push some blank commit to check if these helped?

**Comment by alekgajos** [comment]
I have checked the latest build for this PR at Jenkins and it seems that cppcheck respected the comments now. Here's the latest summary from cppcheck at Jenkins:
image
It seems that 79 style warnings are gone now (and "function is never used" is a style warning).

**Review by alekgajos — APPROVED** [review]

**Pull request merged**
